# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: models/event_export.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'models/event_export.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19models/event_export.proto\x12\x0eparrygg.models\"\xc5\x01\n\x0b\x45ventExport\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\t\x12\x31\n\x06status\x18\x03 \x01(\x0e\x32!.parrygg.models.EventExportStatus\x12\x14\n\x0c\x62raacket_url\x18\x04 \x01(\t\x12\x13\n\x0bretry_count\x18\x05 \x01(\x05\x12\x12\n\nlast_error\x18\x06 \x01(\t\x12\x12\n\ncreated_at\x18\x07 \x01(\t\x12\x12\n\nupdated_at\x18\x08 \x01(\t*\xbf\x01\n\x11\x45ventExportStatus\x12#\n\x1f\x45VENT_EXPORT_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n\x1b\x45VENT_EXPORT_STATUS_PENDING\x10\x01\x12#\n\x1f\x45VENT_EXPORT_STATUS_IN_PROGRESS\x10\x02\x12\x1f\n\x1b\x45VENT_EXPORT_STATUS_SUCCESS\x10\x03\x12\x1e\n\x1a\x45VENT_EXPORT_STATUS_FAILED\x10\x04\x42\x18\n\x14gg.parry.grpc.modelsP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models.event_export_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024gg.parry.grpc.modelsP\001'
  _globals['_EVENTEXPORTSTATUS']._serialized_start=246
  _globals['_EVENTEXPORTSTATUS']._serialized_end=437
  _globals['_EVENTEXPORT']._serialized_start=46
  _globals['_EVENTEXPORT']._serialized_end=243
# @@protoc_insertion_point(module_scope)
