# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: models/hierarchy.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'models/hierarchy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16models/hierarchy.proto\x12\x0eparrygg.models\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x01\n\x04Path\x12\n\n\x02id\x18\x01 \x01(\t\x12&\n\x04type\x18\x02 \x01(\x0e\x32\x18.parrygg.models.PathType\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04slug\x18\x04 \x01(\t\x12\x16\n\timage_url\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x33\n\nstart_time\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x01\x88\x01\x01\x42\x0c\n\n_image_urlB\r\n\x0b_start_time\"<\n\rEventSlugPath\x12\x17\n\x0ftournament_slug\x18\x01 \x01(\t\x12\x12\n\nevent_slug\x18\x02 \x01(\t\"P\n\rPhaseSlugPath\x12\x17\n\x0ftournament_slug\x18\x01 \x01(\t\x12\x12\n\nevent_slug\x18\x02 \x01(\t\x12\x12\n\nphase_slug\x18\x03 \x01(\t\"h\n\x0f\x42racketSlugPath\x12\x17\n\x0ftournament_slug\x18\x01 \x01(\t\x12\x12\n\nevent_slug\x18\x02 \x01(\t\x12\x12\n\nphase_slug\x18\x03 \x01(\t\x12\x14\n\x0c\x62racket_slug\x18\x04 \x01(\t\"]\n\tHierarchy\x12#\n\x05paths\x18\x01 \x03(\x0b\x32\x14.parrygg.models.Path\x12+\n\rsibling_paths\x18\x02 \x03(\x0b\x32\x14.parrygg.models.Path*e\n\x08PathType\x12\x18\n\x14PATH_TYPE_TOURNAMENT\x10\x00\x12\x13\n\x0fPATH_TYPE_EVENT\x10\x01\x12\x13\n\x0fPATH_TYPE_PHASE\x10\x02\x12\x15\n\x11PATH_TYPE_BRACKET\x10\x03\x42\x18\n\x14gg.parry.grpc.modelsP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models.hierarchy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024gg.parry.grpc.modelsP\001'
  _globals['_PATHTYPE']._serialized_start=615
  _globals['_PATHTYPE']._serialized_end=716
  _globals['_PATH']._serialized_start=76
  _globals['_PATH']._serialized_end=268
  _globals['_EVENTSLUGPATH']._serialized_start=270
  _globals['_EVENTSLUGPATH']._serialized_end=330
  _globals['_PHASESLUGPATH']._serialized_start=332
  _globals['_PHASESLUGPATH']._serialized_end=412
  _globals['_BRACKETSLUGPATH']._serialized_start=414
  _globals['_BRACKETSLUGPATH']._serialized_end=518
  _globals['_HIERARCHY']._serialized_start=520
  _globals['_HIERARCHY']._serialized_end=613
# @@protoc_insertion_point(module_scope)
