# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/match_game_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'services/match_game_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from models import bracket_pb2 as models_dot_bracket__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!services/match_game_service.proto\x12\x10parrygg.services\x1a\x14models/bracket.proto\"a\n\x16\x43reateMatchGameRequest\x12\x10\n\x08match_id\x18\x01 \x01(\t\x12\x35\n\nmatch_game\x18\x02 \x01(\x0b\x32!.parrygg.models.MatchGameMutation\"H\n\x17\x43reateMatchGameResponse\x12-\n\nmatch_game\x18\x01 \x01(\x0b\x32\x19.parrygg.models.MatchGame\"[\n\x16UpdateMatchGameRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x35\n\nmatch_game\x18\x02 \x01(\x0b\x32!.parrygg.models.MatchGameMutation\"H\n\x17UpdateMatchGameResponse\x12-\n\nmatch_game\x18\x01 \x01(\x0b\x32\x19.parrygg.models.MatchGame\"$\n\x16\x44\x65leteMatchGameRequest\x12\n\n\x02id\x18\x01 \x01(\t\"H\n\x17\x44\x65leteMatchGameResponse\x12-\n\nmatch_game\x18\x01 \x01(\x0b\x32\x19.parrygg.models.MatchGame\"z\n\x1c\x42\x61tchReportMatchGamesRequest\x12\x10\n\x08match_id\x18\x01 \x01(\t\x12\x36\n\x0bmatch_games\x18\x02 \x03(\x0b\x32!.parrygg.models.MatchGameMutation\x12\x10\n\x08\x66inalize\x18\x03 \x01(\x08\"O\n\x1d\x42\x61tchReportMatchGamesResponse\x12.\n\x0bmatch_games\x18\x01 \x03(\x0b\x32\x19.parrygg.models.MatchGame2\xcc\x03\n\x10MatchGameService\x12h\n\x0f\x43reateMatchGame\x12(.parrygg.services.CreateMatchGameRequest\x1a).parrygg.services.CreateMatchGameResponse\"\x00\x12h\n\x0fUpdateMatchGame\x12(.parrygg.services.UpdateMatchGameRequest\x1a).parrygg.services.UpdateMatchGameResponse\"\x00\x12h\n\x0f\x44\x65leteMatchGame\x12(.parrygg.services.DeleteMatchGameRequest\x1a).parrygg.services.DeleteMatchGameResponse\"\x00\x12z\n\x15\x42\x61tchReportMatchGames\x12..parrygg.services.BatchReportMatchGamesRequest\x1a/.parrygg.services.BatchReportMatchGamesResponse\"\x00\x42\x1a\n\x16gg.parry.grpc.servicesP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.match_game_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026gg.parry.grpc.servicesP\001'
  _globals['_CREATEMATCHGAMEREQUEST']._serialized_start=77
  _globals['_CREATEMATCHGAMEREQUEST']._serialized_end=174
  _globals['_CREATEMATCHGAMERESPONSE']._serialized_start=176
  _globals['_CREATEMATCHGAMERESPONSE']._serialized_end=248
  _globals['_UPDATEMATCHGAMEREQUEST']._serialized_start=250
  _globals['_UPDATEMATCHGAMEREQUEST']._serialized_end=341
  _globals['_UPDATEMATCHGAMERESPONSE']._serialized_start=343
  _globals['_UPDATEMATCHGAMERESPONSE']._serialized_end=415
  _globals['_DELETEMATCHGAMEREQUEST']._serialized_start=417
  _globals['_DELETEMATCHGAMEREQUEST']._serialized_end=453
  _globals['_DELETEMATCHGAMERESPONSE']._serialized_start=455
  _globals['_DELETEMATCHGAMERESPONSE']._serialized_end=527
  _globals['_BATCHREPORTMATCHGAMESREQUEST']._serialized_start=529
  _globals['_BATCHREPORTMATCHGAMESREQUEST']._serialized_end=651
  _globals['_BATCHREPORTMATCHGAMESRESPONSE']._serialized_start=653
  _globals['_BATCHREPORTMATCHGAMESRESPONSE']._serialized_end=732
  _globals['_MATCHGAMESERVICE']._serialized_start=735
  _globals['_MATCHGAMESERVICE']._serialized_end=1195
# @@protoc_insertion_point(module_scope)
